version: "3"
services:

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks: 
      - tethys-net

  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    tty: true
    networks: 
      - tethys-net
    command: ["bin/bash"]

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    tty: true
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    networks: 
      - tethys-net

networks:
  tethys-net:
    name: tethys-net
