headers:
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
permits:
  - name: middle_fork
    permit_id: 234623
    division_id: 377
  - name: deso_gray
    permit_id: 233393
    division_id: 282
  - name: main_salmon
    permit_id: 234622
    division_id: 376
  - name: selway
    permit_id: 234624
    division_id: 378
  - name: yampa
    permit_id: 250014
    division_id: 371
  - name: gates_of_lodore
    permit_id: 250014
    division_id: 380
  - name: salt
    permit_id: 249275
    division_id: 1249275
  - name: rogue
    permit_id: 251982
    division_id: 833
    by_group_size: True
  - name: hells_canyon
    permit_id: 234625
    division_id: 379
