name: tethys
on:
  push:
    branches:
      - main
# set permissions for AWS creds
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: deploy scraper lambda
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::***REMOVED***:role/github_actions
          role-session-name: tethys_github_action
          aws-region: us-east-2
      - name: checkout source code
        uses: actions/checkout@v1
      - name: build docker container
        run: |
          cd scraper
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ***REMOVED***.dkr.ecr.us-east-2.amazonaws.com
          docker build -t tethys_scraper .
          docker tag tethys_scraper:latest ***REMOVED***.dkr.ecr.us-east-2.amazonaws.com/tethys_scraper:latest
          docker push ***REMOVED***.dkr.ecr.us-east-2.amazonaws.com/tethys_scraper:latest
      - name: update lambda function
        run: |
          aws lambda update-function-code --function-name permitScrape \
          --image-uri ***REMOVED***.dkr.ecr.us-east-2.amazonaws.com/tethys_scraper:latest
